AppBundle\Entity\Projet:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ProjetRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
            column: Nom
        startdate:
            type: datetime
        enddate:
            type: string
            length: 255
    lifecycleCallbacks: {  }
